<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GreenWorld.Application\GreenWorld.Application.csproj" />
      <ProjectReference Include="..\GreenWorld.Domain\GreenWorld.Domain.csproj" />
      <ProjectReference Include="..\GreenWorld.Infrastructure\GreenWorld.Infrastructure.csproj" />
      <ProjectReference Include="..\GreenWorld.SharedKernel\GreenWorld.SharedKernel.csproj" />
    </ItemGroup>

</Project>
