// <auto-generated />
using System;
using GreenWorld.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenWorld.Infrastructure.Persistence.Migrations;

[DbContext(typeof(GreenWorldDbContext))]
partial class GreenWorldDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("GreenWorld.Domain.Models.Neighbourhood", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<DateTimeOffset>("SimulationStart").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.ToTable("neighbourhoods");
        });

        modelBuilder.Entity("GreenWorld.Domain.Models.NeighbourhoodAggregateSnapshot", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTimeOffset>("At").HasColumnType("timestamp with time zone");
            b.Property<double>("CloudCover").HasColumnType("double precision");
            b.Property<double>("CumulativeConsumedKwh").HasColumnType("double precision");
            b.Property<double>("CumulativeGeneratedKwh").HasColumnType("double precision");
            b.Property<double>("IrradianceFactor").HasColumnType("double precision");
            b.Property<Guid>("NeighbourhoodId").HasColumnType("uuid");
            b.Property<string>("Season").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<double>("TemperatureCelsius").HasColumnType("double precision");
            b.Property<double>("TotalConsumptionKw").HasColumnType("double precision");
            b.Property<double>("TotalGenerationKw").HasColumnType("double precision");
            b.HasKey("Id");
            b.HasIndex("NeighbourhoodId", "At");
            b.ToTable("neighbourhood_aggregate_snapshots");
        });

        modelBuilder.Entity("GreenWorld.Domain.Models.Sites.MeteredSite", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<Guid>("NeighbourhoodId").HasColumnType("uuid");
            b.Property<string>("site_type").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.HasIndex("NeighbourhoodId");
            b.ToTable("sites");
            b.HasDiscriminator<string>("site_type").HasValue("MeteredSite");
            b.UseTphMappingStrategy();
        });

        modelBuilder.Entity("GreenWorld.Domain.Models.Assets.Asset", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<double>("CapacityKwp").HasColumnType("double precision");
            b.Property<double>("CumulativeConsumedKwh").HasColumnType("double precision");
            b.Property<double>("CumulativeGeneratedKwh").HasColumnType("double precision");
            b.Property<string>("Direction").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<string>("Kind").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
            b.Property<double>("LastPowerKw").HasColumnType("double precision");
            b.Property<DateTimeOffset?>("LastReadingAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<double>("RatedPowerKw").HasColumnType("double precision");
            b.Property<double>("ScaleFactor").HasColumnType("double precision");
            b.Property<int>("Seed").HasColumnType("integer");
            b.Property<Guid>("SiteId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("SiteId");
            b.ToTable("assets");
        });

        modelBuilder.Entity("GreenWorld.Domain.Models.Events.MeterReadingEvent", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid>("AssetId").HasColumnType("uuid");
            b.Property<string>("Direction").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<double>("EnergyKwh").HasColumnType("double precision");
            b.Property<DateTimeOffset>("OccurredAt").HasColumnType("timestamp with time zone");
            b.Property<double>("PowerKw").HasColumnType("double precision");
            b.Property<DateTimeOffset>("ReceivedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("AssetId", "OccurredAt");
            b.ToTable("meter_readings");
        });

        modelBuilder.Entity("GreenWorld.Domain.Models.Sites.Household", b =>
        {
            b.HasBaseType("GreenWorld.Domain.Models.Sites.MeteredSite");
            b.HasDiscriminator().HasValue("Household");
        });

        modelBuilder.Entity("GreenWorld.Domain.Models.Sites.PublicFacility", b =>
        {
            b.HasBaseType("GreenWorld.Domain.Models.Sites.MeteredSite");
            b.HasDiscriminator().HasValue("PublicFacility");
        });

        modelBuilder.Entity("GreenWorld.Domain.Models.Sites.MeteredSite", b =>
        {
            b.HasOne("GreenWorld.Domain.Models.Neighbourhood", null)
                .WithMany("Sites")
                .HasForeignKey("NeighbourhoodId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("GreenWorld.Domain.Models.Assets.Asset", b =>
        {
            b.HasOne("GreenWorld.Domain.Models.Sites.MeteredSite", null)
                .WithMany("Assets")
                .HasForeignKey("SiteId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("GreenWorld.Domain.Models.Neighbourhood", b =>
        {
            b.Navigation("Sites");
        });

        modelBuilder.Entity("GreenWorld.Domain.Models.Sites.MeteredSite", b =>
        {
            b.Navigation("Assets");
        });
    }
}
